---
- hosts: hammerdb
  name: Run HammerDB - rampup test
  gather_facts: false
  become: true

  collections:
    - edb_devops.edb_postgres

  tasks:
    - name: Copy the exec-hdb-rampup.sh file
      ansible.builtin.copy:
        src: exec-hdb-rampup.sh
        dest: "{{ hammerdb_data_path }}/exec-hdb-rampup.sh"
        mode: "0755"

    - name: Execute the ramping up workload
      ansible.builtin.shell: >
       {{ hammerdb_data_path }}/exec-hdb-rampup.sh >> {{ hammerdb_data_path }}/xdb_nopm_catchup_time.csv
      args:
        executable: /bin/bash
      environment:
        PG_HOST: "{{ hostvars['xdb1'].private_ip }}"
        PG_HOST2: "{{ hostvars['xdb2'].private_ip }}"
        HAMMERDB_BIN_PATH: "{{ hammerdb_data_path }}"
        TPCC_WAREHOUSE: "{{ TPCC_WAREHOUSE }}"
        TPCC_RAMPUP: "{{ TPCC_RAMPUP }}"
        TPCC_DURATION: "{{ TPCC_DURATION }}"
        TPCC_MIN_VUSERS: "{{ TPCC_MIN_VUSERS }}"
        TPCC_MAX_VUSERS: "{{ TPCC_MAX_VUSERS }}"
        TPCC_STEP_VUSERS: "{{ TPCC_STEP_VUSERS }}"
        PG_DBNAME: "{{ xdb_dbname }}"
      async: 180000
      poll: 60

    - name: Fetch data files
      ansible.builtin.fetch:
        src: "{{ hammerdb_data_path }}/{{ item }}"
        dest: "./benchmark_data/{{ item }}"
        flat: true
      loop:
      - "xdb_nopm_catchup_time.csv"

- hosts: localhost
  name: post-processing on localhost
  gather_facts: false
  become: false
  tasks:
    - name: Generate final data points and chart
      ansible.builtin.shell:
        cmd: |
          # Some distros use python for python3 since python2 is EOL
          if command -v python3 > /dev/null
          then
            PLAYBOOK_PYTHON="python3"
          else
            PLAYBOOK_PYTHON="python"
          fi
          $PLAYBOOK_PYTHON {{ playbook_dir }}/post-processing.py

    - name: Copy data to results directory
      ansible.builtin.copy:
        src: "./benchmark_data/"
        dest: "{{ results_directory }}/"

    - name: Discard temporary data directory
      ansible.builtin.file:
        path: "./benchmark_data/"
        state: absent
