---
- hosts: localhost
  name: Validate DBT2 drivers and values
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  tasks:       
  - name: TEST
    local_action:
      module: ansible.builtin.debug
      msg: "test"
  - name: RESULTS_DIRECTORY
    ansible.builtin.debug:
      msg: "{{ results_directory }}"

